---
- name: export all aap config
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Export all assets
      awx.awx.export:
        all: True
      register: export_output

    - name:  all assets from our export
      ansible.builti.debug:
        var: export_output
      
    - name: Display export completion message
      debug:
        msg: "AAP configuration export completed successfully."
