---
- name: export all aap config
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Export all assets
      awx.awx.export:
        all: True
      register: export_output

    - name: Import all assets from our export
      import:
        assets: "{{ export_output.assets }}"
      
    - name: Display export completion message
      debug:
        msg: "AAP configuration export completed successfully."
