---
- name: export all aap config
  hosts: ctrl
  gather_facts: true
  tasks:
    - name: Display start message
      debug:
        msg: "Starting AAP configuration Import process."

    - name: command to import all assets
      command: >
        ls -alh    
      delegate_to: localhost

    - name: Export all assets
      awx.awx.import:
        controller_host: 192.168.64.67:8443
        controller_username: admin
        controller_password: primod123
        validate_certs: false
        assets: "{{ lookup('file', 'org.json') | from_json() }}"
      delegate_to: localhost

    - name: Display export completion message
      debug:
        msg: "AAP configuration Import completed successfully."

